// AUTH
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const LOGOUT = "LOGOUT";


// BOOKS
export const GET_SINGLE_BOOK = "GET_SINGLE_BOOK";
export const SET_SINGLE_BOOK = "SET_SINGLE_BOOK";
export const UPDATE_SINGLE_BOOK = "UPDATE_SINGLE_BOOK";
export const LOADING_SINGLE_BOOK = "LOADING_SINGLE_BOOK";
export const SET_ALL_BOOKS = "SET_ALL_BOOKS";
export const LOADING_ALL_BOOKS = "LOADING_ALL_BOOKS";
export const RELOAD_BOOKS = "RELOAD_BOOKS";


// USERS
export const UPDATING_USER_INFO = "UPDATING_USER_INFO";
export const FETCH_USER_INFO = "FETCH_USER_INFO";
